---
#######################################################################################################################
# EXAMPLE UNIVERSAL FORWARDER DEPLOYMENT
#######################################################################################################################
- hosts: local
  vars_files:
    - ../vars/default.yml 
  tasks:
    # download splunk enterprise and uf to /tmp/splunk.rpm and /tmp/splunkuf.rpm
    - name: Download Splunk
      include_role:
        name: download_splunk
    
    - name: Create Splunk User
      import_tasks: ../roles/pre_config/tasks/add_splunk_user_accounts.yml

#######################################################################################################################
# INSTALL UNIVERSAL FORWADER
#######################################################################################################################

- hosts: splunk_universal_forwarder
  vars_files:
    - ../vars/default.yml
  gather_facts: True
  pre_tasks:
    # Include additional variables as required
    - name: Include Global S2S Variable
      include_vars: ../vars/splunk_s2s.yml

    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml
      
    - name: Include Deployment Client Variable
      include_vars: ../vars/splunk_deployment_client.yml

    - name: Include Universal Forwarder Variable
      include_vars: ../vars/splunk_universal_forwarder.yml

  post_tasks:
  tasks:

    # UNIVERSAL FORWARDER - check for splunk_universal_forwarder role
    - name: Splunk splunk_universal_forwarder tasks
      include_role:
        name: splunk_universal_forwarder