all:
  children:
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk:
          hostname: "{{ inventory_hostname }}"
      children:
        
        splunk_deployment_server:
          vars:
            splunk:
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
        splunk_license_master:
          vars:
            splunk:
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
        splunk_deployer:
          vars:
            splunk:
              # Note: this server has two roles (LM and DP) - we need to set the role to 
              # splunk_license_master or it will get added as a local slave to itself.
              # This cases delays in deployment and general non-goodness :)
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"