all:
  children:
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk:
          hostname: "{{ inventory_hostname }}"
      children:
        splunk_license_master:
          vars:
            splunk:
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local: