all:
  children:
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk:
          hostname: "{{ inventory_hostname }}"
      children:
        splunk_cluster_master:
          vars:
            splunk:
              role: "splunk_cluster_master"
          hosts: 
            splkcm1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
        splunk_indexer:
          vars:
            splunk:
              role: "splunk_indexer"
          hosts: 
            splkidx1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
            splkidx2.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
            splkidx3.psl.local:
              splunk:
                # example of multi site
                site: "{{ 'site2' if splunk.all_sites is defined else splunk_default_site|default(omit) }}"
            splkidx4.psl.local:
              splunk:
                # example of multi site
                site: "{{ 'site2' if splunk.all_sites is defined else splunk_default_site|default(omit) }}"