all:
  children:
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk:
          hostname: "{{ inventory_hostname }}"
      children:
        splunk_standalone:
          children:
            splunk_search_head:
              vars:
                splunk:
                  role: "splunk_standalone"
              hosts: 
                splksh1.psl.local: