all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk_default_site: "{{ 'site1' if 'splunk_indexcluster' in deployment_type else omit }}"
        splunk_cluster_master_host: "{{ groups['splunk_cluster_master'][0] if 'splunk_indexcluster' in deployment_type else omit }}"
        splunk_search_head_cluster_host: "{{ groups['splunk_search_head_captain'][0] if 'splunk_searchheadcluster' in deployment_type else omit }}"
        splunk_deployment_server: "{{ groups['splunk_deployment_server'][0] if 'splunk_deploymentserver' in deployment_type else omit }}"
        splunk_multisite_master: "{{ groups['splunk_cluster_master'][0] if 'splunk_indexcluster' in deployment_type else omit }}"
        splunk:
        
          # disable forwarding if standalone
          forward_servers: "{{ [] if 'splunk_standalone' in deployment_type else omit }}"

          # multisite
          all_sites: "{{ 'site1,site2' if 'splunk_indexcluster' in deployment_type and 'splunk_multisite' in deployment_type  else omit }}"
          multisite_master: "{{ splunk_multisite_master if 'splunk_indexcluster' in deployment_type and 'splunk_multisite' in deployment_type  else omit }}"
          
          # index cluster
          cluster_master_url: "{{ splunk_cluster_master_host if 'splunk_indexcluster' in deployment_type else omit }}"
          
          # searchhead cluster
          search_head_cluster_url: "{{ splunk_search_head_cluster_host if 'splunk_searchheadcluster' in deployment_type else omit }}"
          
          hostname: "{{ inventory_hostname }}"
      children:
        splunk_standalone:
          vars:
            splunk:
              role: "splunk_standalone"
          hosts: 
            splksh1.psl.local:
        splunk_search_head_captain:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
        splunk_search_head:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host }}"
            splunk:
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
            splksh2.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
            splksh3.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
        splunk_cluster_master:
          vars:
            splunk:
              role: "splunk_cluster_master"
          hosts: 
            splkcm1.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
        splunk_indexer:
          vars:
            splunk:
              role: "splunk_indexer"
          hosts: 
            splkidx1.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
            splkidx2.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
            splkidx3.psl.local:
              splunk:
                # example of multi site
                site: "{{ 'site2' if splunk.all_sites is defined else splunk_default_site }}"
            splkidx4.psl.local:
              splunk:
                # example of multi site
                site: "{{ 'site2' if splunk.all_sites is defined else splunk_default_site }}"
        splunk_deployment_server:
          vars:
            splunk:
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
        splunk_license_master:
          vars:
            splunk:
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
        splunk_deployer:
          vars:
            splunk:
              # Note: this server has two roles (LM and DP) - we need to set the role to 
              # splunk_license_master or it will get added as a local slave to itself.
              # This cases delays in deployment and general non-goodness :)
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
              splunk:
                site: "{{ splunk_default_site }}"
        splunk_distributed_monitoring_console:
          vars:
            splunk:
              role: "splunk_distributed_monitoring_console"
          hosts:
            splkdp1.psl.local: