all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
      children:
        splunk_standalone:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_standalone"
          hosts: 
              splksh1.psl.local:
                site_number: 1
          # leave this here to stop triggering event forwarding :(=====
          children:
            splunk_search_head:
              hosts:
        splunk_search_head_captain:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              site_number: 1
        splunk_search_head:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              site_number: 1
            splksh2.psl.local:
              site_number: 1
            splksh3.psl.local:              
              site_number: 1
        splunk_cluster_master:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_cluster_master"
          hosts: 
            splkcm1.psl.local:
              site_number: 1
        splunk_indexer:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_indexer"
          hosts: 
            splkidx1.psl.local:
              site_number: 1
            splkidx2.psl.local:
              site_number: 1
            splkidx3.psl.local:
              site_number: 2
            splkidx4.psl.local:
              site_number: 2
        splunk_deployment_server:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
              site_number: 1
        splunk_license_master:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
              site_number: 1
        splunk_deployer:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              # Note: this server has two roles (LM and DP) - we need to set the role to 
              # splunk_license_master or it will get added as a local slave to itself.
              # This cases delays in deployment and general non-goodness :)
              role: "splunk_deployer"
          hosts: 
            splkdp1.psl.local:
              site_number: 1
        splunk_distributed_monitoring_console:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_distributed_monitoring_console"
          hosts:
            splkdp1.psl.local:
              site_number: 1