all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
      children:
        splunk_standalone:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_standalone"
          hosts: 
              splk-sh1.psl.local:
                site_number: 1
          # leave this here to stop triggering event forwarding :(=====
          children:
            splunk_search_head:
              hosts:
        splunk_search_head_captain:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splk-sh1.psl.local:
              site_number: 1
        splunk_search_head:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splk-sh1.psl.local:
              site_number: 1
            splk-sh2.psl.local:
              site_number: 1
            splk-sh3.psl.local:              
              site_number: 1
        splunk_cluster_master:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_cluster_master"
          hosts: 
            splk-cm1.psl.local:
              site_number: 1
        splunk_indexer:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_indexer"
          hosts: 
            splk-idx1.psl.local:
              site_number: 1
            splk-idx2.psl.local:
              site_number: 1
            splk-idx3.psl.local:
              site_number: 2
            splk-idx4.psl.local:
              site_number: 2
        splunk_deployment_server:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_license_master"
          hosts: 
            splk-dp1.psl.local:
              site_number: 1
        splunk_license_master:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_license_master"
          hosts: 
            splk-dp1.psl.local:
              site_number: 1
        splunk_deployer:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_deployer"
          hosts: 
            splk-shd1.psl.local:
              site_number: 1
        splunk_heavy_forwarder:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_heavy_forwarder"
          hosts: 
            splk-hec1.psl.local:
              site_number: 1
        splunk_universal_forwarder:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_universal_forwarder"
          hosts: 
            splk-ids1.psl.local:
              site_number: 1
        splunk_distributed_monitoring_console:
          vars:
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: "splunk_distributed_monitoring_console"
          hosts:
            splk-dp1.psl.local:
              site_number: 1