---
# tasks file for splunk_server

# copy install files
- name: Copy splunk enterprise installation
  copy:
    src: /tmp/splunk.rpm
    dest: /tmp/splunk.rpm
  when:
    - "(not 'splunk_universal_forwarder' in groups) or (not inventory_hostname in groups['splunk_universal_forwarder'])"

- name: Copy splunk universal forwarder installation
  copy:
    src: /tmp/splunkuf.rpm
    dest: /tmp/splunkuf.rpm
  when:
    - "'splunk_universal_forwarder' in groups"
    - inventory_hostname in groups['splunk_universal_forwarder']

# copy license files
- name: Copy splunk license
  copy:
    src: "{{ splunk.license_uri }}"
    dest: "{{ splunk.license_uri }}"
  when:
    - "(not 'splunk_universal_forwarder' in groups) or (not inventory_hostname in groups['splunk_universal_forwarder'])"
  ignore_errors: true

# copy deployment apps
- name: Copy deployment apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - splunk_install_deployment_apps is defined and splunk_install_deployment_apps
    - "'splunk_deployment_server' in groups"
    - inventory_hostname in groups['splunk_deployment_server']
  with_items:
    - /tmp/indexes.tgz
    - /tmp/inputs_forwarded_events.tgz
    - /tmp/inputs_win_dns.tgz
    - /tmp/Splunk_TA_windows.tgz  
    - /tmp/inputs_suricata.tgz 
    - /tmp/splunk_inventory.csv
    - /tmp/lab_inventory.csv
  ignore_errors: true
  become: "{{ splunk.user }}"

# copy search head cluster apps
- name: Copy search head cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - (splunk_enable_shc is defined and splunk_install_search_head_apps is defined) and (splunk_enable_shc and splunk_install_search_head_apps)
    - "'splunk_deployer' in groups"
    - inventory_hostname in groups['splunk_deployer']
  with_items:
    - /tmp/indexes.tgz
  ignore_errors: true
  become: "{{ splunk.user }}"

# copy search head apps
- name: Copy search head cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - (splunk_enable_shc is defined and splunk_install_search_head_apps is defined) and (not splunk_enable_shc and splunk_install_search_head_apps)
    - "('splunk_search_head' in groups and inventory_hostname in groups['splunk_search_head']) or ('splunk_search_head' in groups and inventory_hostname in groups['splunk_standalone'])"
  with_items:
    - /tmp/indexes.tgz
  ignore_errors: true
  become: "{{ splunk.user }}"

# copy index cluster apps
- name: Copy indexer cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - (splunk_enable_idxc is defined and splunk_install_indexer_apps is defined) and (splunk_enable_idxc and splunk_install_indexer_apps)
    - inventory_hostname in groups['splunk_cluster_master']
  with_items:
    - /tmp/indexes.tgz
    - /tmp/props_win_dns.tgz
    - /tmp/transforms_forwarded_events.tgz
    - /tmp/props_suricata.tgz
  ignore_errors: true
  become: "{{ splunk.user }}"

# copy indexer apps
- name: Copy indexer apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - (splunk_enable_idxc is defined and splunk_install_indexer_apps is defined) and (not splunk_enable_idxc and splunk_install_indexer_apps )
    - "'splunk_indexer' in groups"
    - inventory_hostname in groups['splunk_indexer'] 
  with_items:
    - /tmp/indexes.tgz
    - /tmp/props_win_dns.tgz
    - /tmp/transforms_forwarded_events.tgz
    - /tmp/props_suricata.tgz
  ignore_errors: true
  become: "{{ splunk.user }}"
