---
# tasks file for splunk_server

# copy install files
- name: Copy splunk installation
  copy:
    src: /tmp/splunk.rpm
    dest: /tmp/splunk.rpm
  when:
    - not inventory_hostname in groups['splunk_universal_forwarder']

- name: Copy splunk installation
  copy:
    src: /tmp/splunkuf.rpm
    dest: /tmp/splunkuf.rpm
  when:
    - inventory_hostname in groups['splunk_universal_forwarder']

# copy install files
- name: Copy splunk license
  copy:
    src: /tmp/splunk.lic
    dest: /tmp/splunk.lic
  when:
    - not inventory_hostname in groups['splunk_universal_forwarder']

# copy deployment apps
- name: Copy deployment apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - splunk_install_deployment_apps
    - inventory_hostname in groups['splunk_deployment_server']
  with_items:
    - /tmp/indexes.tgz
    - /tmp/inputs_forwarded_events.tgz
    - /tmp/inputs_win_dns.tgz  
    - /tmp/inputs_suricata.tgz 

# copy search head cluster apps
- name: Copy search head cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - splunk_enable_shc and splunk_install_search_head_apps
    - inventory_hostname in groups['splunk_deployer']
  with_items:
    - /tmp/indexes.tgz

# copy search head apps
- name: Copy search head cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - not splunk_enable_shc and splunk_install_search_head_apps
    - (inventory_hostname in groups['splunk_search_head'] or inventory_hostname in groups['splunk_standalone'])
  with_items:
    - /tmp/indexes.tgz

# copy index cluster apps
- name: Copy indexer cluster apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - splunk_enable_idxc and splunk_install_indexer_apps
    - inventory_hostname in groups['splunk_cluster_master']
  with_items:
    - /tmp/indexes.tgz
    - /tmp/props_win_dns.tgz

# copy indexer apps
- name: Copy indexer apps
  copy:
    src: "{{ item }}"
    dest: /tmp
  when: 
    - not splunk_enable_idxc and splunk_install_indexer_apps 
    - inventory_hostname in groups['splunk_indexer'] 
  with_items:
    - /tmp/indexes.tgz
    - /tmp/props_win_dns.tgz
    - /tmp/transforms_forwarded_events.tgz