---
# tasks file for splunk_server
- name: Register firewalld status
  command: systemctl status "{{ item }}"
  with_items:
  - firewalld
  register: firewalld_status
  ignore_errors: yes
  become: yes

- name: Splunk web proxy port
  firewalld:
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk web firewall port
  firewalld:
    port: 8000/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk management firewall port
  firewalld:
    port: 8089/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk HEC firewall port
  firewalld:
    port: 8088/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(inventory_hostname in groups['splunk_indexer']|default([],true)) and (firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk indexer firewall port
  firewalld:
    port: 9997/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(inventory_hostname in groups['splunk_indexer']|default([],true)) and (firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk index cluster replication firewall port
  firewalld:
    port: 9887/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(inventory_hostname in groups['splunk_indexer']|default([],true)) and (firewalld_status.results[0].rc == 0)"
  become: yes

- name: Splunk search head cluster replication firewall port
  firewalld:
    port: 9887/tcp
    permanent: yes
    immediate: yes
    state: enabled
  when: "(inventory_hostname in groups['splunk_search_head']|default([],true)) and (firewalld_status.results[0].rc == 0)"
  become: yes