#   Version 7.0.2
#
# This file contains possible attribute/value pairs for saved search entries in
# savedsearches.conf.  You can configure saved searches by creating your own
# savedsearches.conf.
#
# There is the default savedsearches.conf in $SPLUNK_HOME/etc/apps/Splunk_ML_Toolkit/default. To
# set custom configurations, place a savedsearches.conf in
# $SPLUNK_HOME/etc/apps/Splunk_ML_Toolkit/local/.  You must restart Splunk to enable configurations.
#
# To learn more about configuration files (including precedence) please see the
# documentation located at
# http://docs.splunk.com/Documentation/Splunk/latest/Admin/Aboutconfigurationfiles

[default]
args.mltk.experiment = [0|1]
* default to false
* If it sets to true, the saved search is a MLTK experiment type of saved search (schedule training or alert).

args.mltk.experiment.alert.actualField = <string>
* the field produced by applying the algorithm used in the comparision
* used in condition(s): num_predicted_value, r_squared_value, different_predicted_value

args.mltk.experiment.alert.clusterId = <string>
* default to 0
* used in condition(s): cluster_id_count

args.mltk.experiment.alert.comparator = <string>
* default to '>'
* the operator to use
* used in condition(s): num_outlier_count, num_predicted_value, cluster_id_count, cat_predicted_value

args.mltk.experiment.alert.condition = <string>
* Required
* the custom trigger condition for an experiment alert, can be expanded to have more values.
* Possible values: 'numeric_outlier_count', 'categorical_predicted_value', 'cluster_id_count', 'categorical_outlier_count', 'numeric_predicted_value', 'smart_outlier_detection'.

args.mltk.experiment.alert.count = <string>
* default to 0
* used in condition(s): num_outlier_count, cat_outlier_count

args.mltk.experiment.alert.experimentType = <string>
* Required
* The type of experiment where the alert is generated from
* Possible values:
* 'predict_numeric_fields', 'predict_categorical_fields', 'detect_numeric_outliers', 'detect_categorical_outliers',
* 'forecast_time_series', 'cluster_numeric_events'

args.mltk.experiment.alert.field = <string>
* the field produced by applying the algorithm used in the comparision
* used in condition(s): num_predicted_value, cat_predicted_value, different_predicted_value

args.mltk.experiment.alert.fields = <string>
* default to '[]'
* a list of field names encoded in JSON
* used in condition(s): cat_outlier_count, multi_numeric_predicted_values

args.mltk.experiment.alert.firstCount = <int>
* default to 0
* used in condition(s): cluster_id_count

args.mltk.experiment.alert.firstValue = <int>
* default to 0
* the value to compare to the selected field
* used in condition(s): num_predicted_value

args.mltk.experiment.alert.integerFields = <string>
* default to '[]'
* the possible integer values which the cluster id can have
* used in condition(s): 'cluster_id_range'

args.mltk.experiment.alert.probableCauseFields = <string>
* default to '[]'
* a list of field names encoded in JSON
* used in condition(s): cat_outlier_count

args.mltk.experiment.alert.secondCount = <int>
* default to 0
* used in condition(s): cluster_id_count

args.mltk.experiment.alert.secondValue = <int>
* default to 0
* the value to compare to if the operator requires a second value
* used in condition(s): num_predicted_value

args.mltk.experiment.alert.selectedFields = <string>
* default to '[]'
* a list of values encoded in JSON
* used in condition(s): multi_numeric_predicted_values

args.mltk.experiment.alert.selectProbableCause = [0|1]
* default to 0
* used in condition(s): cat_outlier_count

args.mltk.experiment.alert.type = <string>
* Deprecated, will replaced by experimentType
* the type of alert generated by applying a model
* possible values:
*   NumericValue, CategoricalOutlierCount, CategoricalValue, ClusterEventCount, NumericOutlierCount:

args.mltk.experiment.alert.useMLTKCondition = [0|1]
* default to true
* whether an alert trigger condition uses MLTK specific ones
* If true, this saved search is using a custom trigger condition specific to MLTK Experiments

args.mltk.experiment.alert.values = <string>
* default to '[]'
* a list of values encoded in JSON
* used in condition(s): cat_predicted_value

args.mltk.experiment.title = <string>
* A human readable title of experiment type of saved search, since the original 'name' field is set to uuid.
