all:
  children:
    splunk:
      vars:
        ansible_connection: ssh
        ansible_system: Linux
        splunk:
          hostname: "{{ inventory_hostname }}"
      children:
        splunk_search_head_captain:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              hostname: "{{ inventory_hostname }}"
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
        splunk_search_head:
          vars:
            is_captain: "{{ inventory_hostname == search_head_cluster_host|default(omit) }}"
            splunk:
              role: 
                "{{ 'splunk_search_head_captain' if is_captain else 'splunk_search_head' }}"
          hosts: 
            splksh1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
            splksh2.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
            splksh3.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"
        splunk_deployer:
          vars:
            splunk:
              # Note: this server has two roles (LM and DP) - we need to set the role to 
              # splunk_license_master or it will get added as a local slave to itself.
              # This cases delays in deployment and general non-goodness :)
              role: "splunk_license_master"
          hosts: 
            splkdp1.psl.local:
              splunk:
                site: "{{ splunk_default_site|default(omit) }}"