---
ansible_post_tasks: null
ansible_pre_tasks: null
hide_password: false
retry_delay: 6
retry_num: 60
wait_for_splunk_retry_num: 60
shc_sync_retry_num: 60
splunk_home_ownership_enforcement: true
cert_prefix: https

config:
  baked: default.yml
  defaults_dir: /tmp/defaults
  env:
    headers: null
    var: SPLUNK_DEFAULTS_URL
    verify: true
  host:
    headers: null
    url: null
    verify: true
  max_delay: 60
  max_retries: 3
  max_timeout: 1200

splunk:
  search_head_captain_url: null
  apps_location: null
  enable_service: true
  admin_user: admin
  allow_upgrade: true
  build_location: /tmp/splunk.rpm
  license_master_included: false
  license_uri: /tmp/splunk.lic
  build_remote_src: true
  app_paths:
    default: /opt/splunk/etc/apps
    deployment: /opt/splunk/etc/deployment-apps
    httpinput: /opt/splunk/etc/apps/splunk_httpinput
    idxc: /opt/splunk/etc/master-apps
    shc: /opt/splunk/etc/shcluster/apps
  exec: /opt/splunk/bin/splunk
  group: splunk
  home: /opt/splunk
  http_enableSSL: true
  http_enableSSL_cert: null
  http_enableSSL_privKey: null
  http_enableSSL_privKey_password: null
  http_port: 8000
  ignore_license: false
  license_download_dest: /tmp/splunk.licences
  nfr_license: /tmp/splunk.lic
  opt: /opt
  password: "{{ lookup('env','SPLUNK_PASSWORD') | default('uOOuUI5D2flIqVXchggUOE+h0DFQV/zo',true) }}"
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  root_endpoint: null
  secret: null
  smartstore: null
  svc_port: 8089
  tar_dir: splunk
  user: splunk
  wildcard_license: true
