---
splunk:
    apps_location: 
        - file:///tmp/indexes.tgz
        
        # windows ta
        - https://splunkbase.splunk.com/app/742/release/7.0.0/download/
        
        # sysmon ta
        - https://splunkbase.splunk.com/app/1914/release/10.6.2/download/