---
splunk:
    apps_location:
        - /tmp/indexes.tgz
        - /tmp/props_win_dns.tgz
        #- /tmp/Splunk_TA_windows.tgz
        - /tmp/transforms_forwarded_events.tgz

        #################################################
        # MITRE ATT&CK APPS
        #################################################

        # getwatchlist
        - https://splunkbase.splunk.com/app/635/release/1.0/download/

        # splunk common information model
        - https://splunkbase.splunk.com/app/1621/release/4.15.0/download/

        # decrypt
        - https://splunkbase.splunk.com/app/2655/release/2.0/download/

        # asn lookup
        - https://splunkbase.splunk.com/app/3531/release/1.1.0/download/

        # timeline
        - https://splunkbase.splunk.com/app/3120/release/1.4.0/download/

        # link analysis
        - https://api.github.com/repos/secops4thewin/link_analysis_app/tarball

        # url toolbox
        - https://splunkbase.splunk.com/app/2734/release/1.8/download/

        # sysmon ta
        - https://splunkbase.splunk.com/app/1914/release/10.6.2/download/

        # force directed viz
        - https://splunkbase.splunk.com/app/3767/release/3.0.1/download/

        # lookup file editor
        - https://splunkbase.splunk.com/app/1724/release/3.3.3/download/

        # punchcard viz
        - https://splunkbase.splunk.com/app/3129/release/1.4.0/download/

        # sankey viz
        - https://splunkbase.splunk.com/app/3112/release/1.4.0/download/

        # splunk machine learning toolkit
        - https://splunkbase.splunk.com/app/2890/release/5.1.0/download/

        # python for scientific computing (linux 64-bit)
        - https://splunkbase.splunk.com/app/2882/release/2.0.0/download/

        # security essentials
        - https://splunkbase.splunk.com/app/3435/release/3.0.6/download/

        # threathunting
        #- https://splunkbase.splunk.com/app/4305/release/1.4.1/download/

        # infosec app for splunk
        - https://splunkbase.splunk.com/app/4240/release/1.5.2/download/

        # sa-investigator
        - https://splunkbase.splunk.com/app/3749/release/2.3.0/download/

        # add-on builder
        - https://splunkbase.splunk.com/app/2962/release/3.0.1/download/

        # app for phantom
        - https://splunkbase.splunk.com/app/3411/release/4.0.35/download/

        # splunk es content update
        - https://splunkbase.splunk.com/app/3449/release/3.18.0/download/

        # ansible monitoring app
        - https://splunkbase.splunk.com/app/4023/release/1.2.2/download/

        # base64
        - https://splunkbase.splunk.com/app/1922/release/1.1/download/

        # custom radar chart viz
        - https://splunkbase.splunk.com/app/3772/release/1.1.1/download/

        # windows ta
        - https://splunkbase.splunk.com/app/742/release/8.1.2/download/
