---
splunk:
    apps_location: 
        - /tmp/indexes.tgz
        
        # jellyfisher
        - https://splunkbase.splunk.com/app/3626/release/0.1.0/download/

        # micrsoft cloud services add-on
        - https://splunkbase.splunk.com/app/3110/release/4.0.1/download/

        # apache add-on
        - https://splunkbase.splunk.com/app/3186/release/1.0.0/download/

        # base64
        - https://splunkbase.splunk.com/app/1922/release/1.1/download/

        # url toolbox
        - https://splunkbase.splunk.com/app/2734/release/1.8/download/

        # ssl certificate checker
        - https://splunkbase.splunk.com/app/3172/release/3.2/download/

        # sa-investigator
        - https://splunkbase.splunk.com/app/3749/release/2.2.2/download/
        
        # windows ta
        - https://splunkbase.splunk.com/app/742/release/7.0.0/download/
        
        # sysmon ta
        - https://splunkbase.splunk.com/app/1914/release/10.6.2/download/

        # windows event log analysis
        - https://splunkbase.splunk.com/app/3067/release/1.5.1/download/

        # infosec app for splunk
        - https://splunkbase.splunk.com/app/4240/release/1.5.2/download/

        # force directed viz
        - https://splunkbase.splunk.com/app/3767/release/3.0.1/download/

        # lookup file editor
        - https://splunkbase.splunk.com/app/1724/release/3.3.3/download/

        # punchcard viz
        - https://splunkbase.splunk.com/app/3129/release/1.4.0/download/

        # sankey viz
        - https://splunkbase.splunk.com/app/3112/release/1.4.0/download/
        
        # splunk machine learning toolkit
        - https://splunkbase.splunk.com/app/2890/release/5.1.0/download/

        # python for scientific computing (linux 64-bit)
        - https://splunkbase.splunk.com/app/2882/release/2.0.0/download/

        # security essentials
        - https://splunkbase.splunk.com/app/3435/release/3.0.6/download/

        # threathunting
        - https://splunkbase.splunk.com/app/4305/release/1.4.1/download/

        
