---
splunk_deployment_server: "{{ lookup('env','SPLUNK_DEPLOYMENT_SERVER') if lookup('env', 'SPLUNK_DEPLOYMENT_SERVER') else groups['splunk_deployment_server'][0] if 'splunk_deployment_server' in groups else groups['splunk_standalone'][0] if 'splunk_standalone' in groups }}"
splunk:
    deployment_server: "{{ splunk_deployment_server }}"