---
# build lookup

- name: Build asn
  command: "{{ splunk.exec }} search \"|asngen | outputlookup asn\" -auth {{ splunk.admin_user }}:{{ splunk.password }}"
  become: yes
  become_user: "{{ splunk.user }}"
  register: build_asn
  until: build_asn.rc == 0
  changed_when: build_asn.rc == 0
  retries: "{{ retry_num }}"
  delay: "{{ retry_delay }}"
  ignore_errors: yes
  no_log: "{{ hide_password }}"