---
#######################################################################################################################
# EXAMPLE DISTRIBUTED DEPLOYMENT
#######################################################################################################################
- hosts: local
  vars_files:
    - ../vars/default.yml 
  pre_tasks:
  tasks:
    - name: Download Splunk
      include_role:
        name: download_splunk

#######################################################################################################################
# INSTALL INDEXER, SEARCH HEAD, DEPLOYMENT SERVER/LICENSE MASTER, UNIVERSAL FORWARDER
#######################################################################################################################

- hosts: splunk_indexer:splunk_search_head:splunk_deployment_server:splunk_license_master:splunk_universal_forwarder
  vars_files:
    - ../vars/default.yml
  gather_facts: True
  pre_tasks:

    # PRE CONFIG - Add users, Ulimits, etc
    - name: Include Pre Config Variable
      include_vars: ../vars/splunk_pre_config_intermediate.yml

    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config
  
    #########################################
    # VARIABLES DEFINING DEPLOYED ENVIRONMENT
    ##########################################
    
    # Include additional variables as required
    - name: Include Global S2S Variable
      include_vars: ../vars/splunk_s2s.yml

    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml

    # setup distributed search for splunk_search_heads
    - name: Include Distributed Search Peer Variable
      include_vars: ../vars/splunk_distributed.yml
      when:
        - "'splunk_search_head' in groups" 
        - inventory_hostname in groups['splunk_search_head']
    
    # setup lisence master url
    - name: Include License Master Variable
      include_vars: ../vars/splunk_license_master.yml
      when:
        - "'splunk_license_master' in groups"
        - "(not 'splunk_universal_forwarder' in groups) or (not inventory_hostname in groups['splunk_universal_forwarder'])"

    # setup deployment server variables
    - name: Include Deployment Server Variable
      include_vars: ../vars/splunk_deployment_server.yml
      when:
        - "'splunk_deployment_server' in groups"
    
    - name: Include Deployment Client Variable
      include_vars: ../vars/splunk_deployment_client.yml
      when:
        - "'splunk_deployment_server' in groups"

    # setup universal forwarder variables
    - name: Include Universal Forwarder Variable
      include_vars: ../vars/splunk_universal_forwarder.yml
      when:
        - "'splunk_universal_forwarder' in groups"
        - inventory_hostname in groups['splunk_universal_forwarder']

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../roles/post_config/tasks/main.yml
  tasks:
    
    # DEPLOYMENTSERVER - check for splunk_deployment_server role
    - name: Splunk splunk_deployment_server tasks
      include_role:
        name: splunk_deployment_server
      when:
        - "'splunk_deployment_server' in groups" 
        - inventory_hostname in groups['splunk_deployment_server']

    # LICENSE MASTER - check for splunk_deployment_server role
    - name: Splunk splunk_license_master tasks
      include_role:
        name: splunk_license_master
      when:
        - "'splunk_license_master' in groups"  
        - inventory_hostname in groups['splunk_license_master']

    # INDEXER - check for splunk_indexer role
    - name: Splunk splunk_indexer tasks
      include_role:
        name: splunk_indexer
      when:
        - "'splunk_indexer' in groups"   
        - inventory_hostname in groups['splunk_indexer']

    # SEARCH HEAD - check for splunk_search_head role
    - name: Splunk splunk_search_head tasks
      include_role:
        name: splunk_search_head
      when:
        - "'splunk_search_head' in groups"    
        - inventory_hostname in groups['splunk_search_head']

    # UNIVERSAL FORWARDER - check for splunk_universal_forwarder role
    - name: Splunk splunk_universal_forwarder tasks
      include_role:
        name: splunk_universal_forwarder
      when:
        - "'splunk_universal_forwarder' in groups" 
        - inventory_hostname in groups['splunk_universal_forwarder']