---
#########################################
# EXAMPLE STANDALONE DEPLOYMENT
#########################################
- hosts: local
  vars_files:
    - ../vars/default-standalone.yml 
  tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ntp_sync
        
    - name: Download Splunk
      include_role:
        name: download_splunk

- hosts: splunk_standalone
  vars_files:
    - ../vars/default-standalone.yml
  gather_facts: True
  pre_tasks:
    # Include additional variables as required
    - name: Include SHC Variable
      include_vars: ../splunk_search_head_cluster.yaml
      when: "{{ splunk_enable_shc is defined and splunk_enable_shc }}"

    - name: Include IDXC Variable
      include_vars: ../splunk_index_cluster.yaml
      when: "{{ splunk_enable_idxc is defined and splunk_enable_idxc }}"

    - name: Include Multisite Variable
      include_vars: ../splunk_multisite.yaml
      when: "{{ splunk_enable_multisite is defined and splunk_enable_multisite }}"

    - name: Include Deployment Server Variable
      include_vars: ../splunk_deployment_server.yaml
      when: "{{ splunk_enable_deployment_server is defined and splunk_enable_deployment_server }}"

    - name: Include Multisite Variable
      include_vars: ../splunk_license_master.yaml
      when: "{{ splunk_enable_license_master is defined and splunk_enable_license_master }}"

    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ntp_sync

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config
  
  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../roles/post_config/tasks/main.yml
  tasks:

    # STANDALONE - check for splunk_standalone role
    - name: Splunk splunk_standalone tasks
      include_role:
        name: splunk_standalone
      when: inventory_hostname in groups['splunk_standalone']