---
#######################################################################################################################
# EXAMPLE DEPLOYMENT SERVER AND UNIVERSAL FORWARDER DEPLOYMENT
#######################################################################################################################
- hosts: local
  vars_files:
    - ../vars/default.yml 
  tasks:
    # download splunk enterprise and uf to /tmp/splunk.rpm and /tmp/splunkuf.rpm
    - name: Download Splunk
      include_role:
        name: download_splunk
 
      
#######################################################################################################################
# INSTALL UNIVERSAL FORWARDER
#######################################################################################################################

- hosts: splunk_universal_forwarder
  vars_files:
    - ../vars/default.yml
  gather_facts: True
  pre_tasks:
    - name: Include Deployment Server Variable
      include_vars: ../vars/splunk_deployment_server.yml
    
    - name: Include Deployment Client Variable
      include_vars: ../vars/splunk_deployment_client.yml
      when: 
        - "('splunk_deployment_server' in groups and inventory_hostname not in groups['splunk_deployment_server']) or ('splunk_deployment_server' not in groups and 'splunk_standalone' in groups and inventory_hostname not in groups['splunk_standalone'])"

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config

    #########################################
    # VARIABLES DEFINING UNIVERSAL FORWARDER CONFIG
    ##########################################
    
    # Include additional variables as required
    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml
    # Set universal_forwarder
    - name: Include Universal Forwarder Variable
      include_vars: ../vars/splunk_universal_forwarder.yml

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../roles/post_config/tasks/main.yml
        
  tasks:

    # UNIVERSAL FORWARDER - check for splunk_universal_forwarder role
    - name: Splunk splunk_universal_forwarder tasks
      include_role:
        name: splunk_universal_forwarder