---
#######################################################################################################################
# EXAMPLE STANDALONE DEPLOYMENT
#######################################################################################################################
- hosts: local
  vars_files:
    - ../vars/default.yml 
  pre_tasks:
  tasks:
    - name: Download Splunk
      include_role:
        name: download_splunk

#######################################################################################################################
# INSTALL STANDALONE
#######################################################################################################################

- hosts: splunk_standalone
  vars_files:
    - ../vars/default.yml
  gather_facts: True
  pre_tasks:

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config
  
    #########################################
    # VARIABLES DEFINING DEPLOYED ENVIRONMENT
    ##########################################
    
    # Include additional variables as required
    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml
      
    - name: Include Standalone Variables
      include_vars: ../vars/splunk_standalone.yml

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../roles/post_config/tasks/main.yml
  tasks:
    - name: Get facts
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/get_facts.yml

    - name: Debug
      debug:
        msg:
          - "Forward Servers: {{ splunk_forward_servers }}"
          - "Splunk: {{ splunk }}"

    # STANDALONE - check for splunk_standalone role
    #- name: Splunk splunk_standalone tasks
    #  include_role:
    #    name: splunk_standalone
    #  when: inventory_hostname in groups['splunk_standalone']