---
#######################################################################################################################
# EXAMPLE STANDALONE DEPLOYMENT
#######################################################################################################################
- hosts: local
  vars_files:
    - ../vars/default-standalone.yml 
  pre_tasks:
  tasks:
    - name: Download Splunk
      include_role:
        name: download_splunk

#######################################################################################################################
# INSTALL STANDALONE
#######################################################################################################################

- hosts: splunk_standalone
  vars_files:
    - ../vars/default-standalone.yml
  gather_facts: True
  pre_tasks:

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config
  
    #########################################
    # VARIABLES DEFINING DEPLOYED ENVIRONMENT
    ##########################################
    
    # Include additional variables as required
    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml
      
    - name: Include Standalone Variables
      include_vars: ../vars/splunk_standalone.yml

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../roles/post_config/tasks/main.yml
  tasks:
    - name: Get facts
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/get_facts.yml

    - name: Debug
      debug:
        msg:
          - "Forward Servers: {{ splunk_forward_servers }}"
          - "Splunk: {{ splunk }}"


    # determine if we need to set up forward servers
    # First, if they are manually specified in the config, use them
    - name: "Setting forward servers fact from config"
      debug:
        msg:
          - "'forward_servers' in splunk"
      when:
        - "'forward_servers' in splunk"

    # If not in the config, is there an index cluster to use?
    # Configure forwarding to indexers directly
    # See: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/forwardersdirecttopeers
    - name: "Setting forward servers fact from index cluster group"
      debug:
        msg:
          - "splunk_forward_servers is not defined"
          - "'splunk_indexer' in groups"
          - "splunk.role != \"splunk_indexer\""
      when:
        - "splunk_forward_servers is not defined"
        - "'splunk_indexer' in groups"
        # Prevent self-forwarding
        - splunk.role != "splunk_indexer"

    # if not specified in config *and*
    # no index clusters, then look for standalone
    # See: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/forwardersdirecttopeers
    - name: "Setting forward servers fact from standalone group"
      debug:
        msg:
          - "splunk_forward_servers is not defined"
          - "'splunk_standalone' in groups"
          - "splunk.role != \"splunk_standalone\""
          - "'splunk_search_head' not in groups"
      when:
        - "splunk_forward_servers is not defined"
        - "'splunk_standalone' in groups"
        # Prevent self-forwarding
        - splunk.role != "splunk_standalone"
        # This part takes a little explaining.  If we have a mixed cluster with no indexers
        # (Only standalone and search heads) we should not automatically forward the data to
        # standalone instances UNLESS they are specified by forward-servers
        - "'splunk_search_head' not in groups"

    
    # STANDALONE - check for splunk_standalone role
    #- name: Splunk splunk_standalone tasks
    #  include_role:
    #    name: splunk_standalone
    #  when: inventory_hostname in groups['splunk_standalone']