###########################################################
# PUSH APPS TO CLUSTER MASTER, DEPLOYMENT_SERVER, DEPLOYER
############################################################

- hosts: local
  vars_files:
    - ../vars/default-clustered.yml
  tasks:

    # compress local apps
    - name: Compress Apps
      include_role:
        name: compress_apps

# STAGE 3 - AFTER INFRATRUCTURE BUILD PUSH APPS IN DISTRIBUTED ENVIRONMENT
- hosts: splunk_deployer:splunk_deployment_server:splunk_cluster_master
  vars_files:
    - ../vars/default-clustered.yml
  gather_facts: True

  pre_tasks:  
    #########################################
    # VARIABLES DEFINING APP INSTALLATION
    ##########################################

    # INDEXER SERVER Apps Variable
    # cluster
    - name: Include Indexer Cluster Apps variables
      include_vars: ../vars/splunk_indexer_apps.yml
      when: 
        - splunk_enable_idxc and splunk_install_indexer_apps 
        - inventory_hostname in groups['splunk_cluster_master']

    # DEPLOYMENT SERVER Apps Variable
    - name: Include Deployment Apps variables
      include_vars: ../vars/splunk_deployment_apps.yml
      when: 
        - splunk_install_deployment_apps
        - inventory_hostname in groups['splunk_deployment_server']

    # SEARCH HEAD Apps Variable
    # cluster
    - name: Include Search Head Cluster Apps variables
      include_vars: ../vars/splunk_search_head_apps.yml
      when: 
        - splunk_enable_shc and splunk_install_search_head_apps
        - inventory_hostname in groups['splunk_deployer']
  tasks:

    #########################################
    # TASKS
    ##########################################

    # DEPLOYMENT SERVER - check for splunk_deployment_server role
    - name: Splunk splunk_deployment_server tasks
      include_tasks: "{{ item }}"
      with_items:
        - ../splunk-ansible/roles/splunk_deployment_server/tasks/create_deployment_apps.yml
        - ../splunk-ansible/roles/splunk_deployment_server/tasks/generate_server_classes.yml
      when: 
        - inventory_hostname in groups['splunk_deployment_server']
        - splunk.apps_location
    
    - name: Reload deployment server
      command: "{{ splunk.exec }} reload deploy-server -auth {{ splunk.admin_user }}:{{ splunk.password }}"
      become: yes
      become_user: "{{ splunk.user }}"
      register: reload_depserver
      until: reload_depserver.rc == 0
      changed_when: reload_depserver.rc == 0
      retries: "{{ retry_num }}"
      delay: "{{ retry_delay }}"
      ignore_errors: yes
      no_log: "{{ hide_password }}"
    
    # CLUSTER MASTER - check for splunk_cluster_master role
    - name: Splunk cluster_master tasks
      include_tasks: "{{ item }}"
      with_items:
        - ../splunk-ansible/roles/splunk_common/tasks/provision_apps.yml
        - ../splunk-ansible/roles/splunk_cluster_master/tasks/prepare_apps_bundle.yml
        - ../splunk-ansible/roles/splunk_cluster_master/tasks/apply_cluster_bundle.yml
        - ../splunk-ansible/roles/splunk_common/tasks/disable_installed_apps.yml
      when:
        - inventory_hostname in groups['splunk_cluster_master']
        - splunk.apps_location


     # DEPLOYER
    - name: Splunk splunk_deployer tasks
      include_tasks: "{{ item }}"
      with_items:
        - ../splunk-ansible/roles/splunk_common/tasks/provision_apps.yml
        - ../splunk-ansible/roles/splunk_deployer/tasks/push_apps_to_search_heads.yml
        - ../splunk-ansible/roles/splunk_common/tasks/disable_installed_apps.yml
      when: 
        - inventory_hostname in groups['splunk_deployer']
        - splunk.apps_location