###########################################################
# PUSH APPS TO CLUSTER MASTER, DEPLOYMENT_SERVER, DEPLOYER
############################################################

- hosts: local
  vars_files:
    - ../vars/default.yml
  tasks:

    # compress local apps
    - name: Compress Apps
      include_role:
        name: compress_apps

# STAGE 3 - AFTER INFRATRUCTURE BUILD PUSH APPS IN DISTRIBUTED ENVIRONMENT
- hosts: splunk_deployer:splunk_deployment_server:splunk_cluster_master
  vars_files:
    - ../vars/default.yml
  gather_facts: True

  pre_tasks:  

    ##########################################
    # VARIABLES DEFINING DEPLOYED ENVIRONMENT
    ##########################################

    # Include additional variables as required
    - name: Include Global S2S Variable
      include_vars: ../vars/splunk_s2s.yml

    - name: Include Global HEC Variable
      include_vars: ../vars/splunk_hec.yml

    - name: Include Global DFS Variable
      include_vars: ../vars/splunk_dfs.yml

    - name: Include SHC Variable
      include_vars: ../vars/splunk_search_head_cluster.yml
    
    - name: Include IDXC Variable
      include_vars: ../vars/splunk_index_cluster.yml

    - name: Include Deployment Server Variable
      include_vars: ../vars/splunk_deployment_server.yml

    - name: Include License Master Variable
      include_vars: ../vars/splunk_license_master.yml
      when: 
        - "(not 'splunk_universal_forwarder' in groups) or (not inventory_hostname in groups['splunk_universal_forwarder'])"

    - name: Include Deployment Client Variable
      include_vars: ../vars/splunk_deployment_client.yml
      when: 
        - "(not 'splunk_deployment_server' in groups) or (not inventory_hostname in groups['splunk_deployment_server'])"
    
    #########################################
    # VARIABLES DEFINING APP INSTALLATION
    ##########################################
    
    # SPLUNK COMMON Apps Variable
    - name: Include Default Apps Vars
      include_vars: ../splunk-ansible/roles/splunk_common/vars/main.yml
    
    # DEPLOYMENT SERVER Apps Variable
    # deployment server
    - name: Include Deployment Apps variables
      include_vars: ../vars/splunk_deployment_apps.yml
      when: 
        - inventory_hostname in groups['splunk_deployment_server']

    # INDEXER SERVER Apps Variable
    # cluster
    - name: Include Indexer Cluster Apps variables
      include_vars: ../vars/splunk_indexer_apps.yml
      when: 
        - inventory_hostname in groups['splunk_cluster_master']

    # SEARCH HEAD Apps Variable
    # cluster
    - name: Include Search Head Cluster Apps variables
      include_vars: ../vars/splunk_search_head_apps.yml
      when: 
        - inventory_hostname in groups['splunk_deployer']
  tasks:

    #########################################
    # TASKS
    ##########################################

    # DEPLOYMENT SERVER - check for splunk_deployment_server role
    - name: Push apps to deployment server
      vars:
        app_url: "{{ item }}"
      copy:
        src: "{{app_url}}"
        dest: "{{app_url}}"
      loop: "{{ splunk.apps_location }}"
      when: 
        - inventory_hostname in groups['splunk_deployment_server']
        - not app_url is match("^(https?|file)://.*")
    
    - name: Install deployment server apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/install_apps.yml
      vars:
        app_url: "{{ item }}"
      loop: "{{ splunk.apps_location }}"
      when: inventory_hostname in groups['splunk_deployment_server']
  
    - name: Find deployment server installed apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/find_installed_apps.yml
      when: inventory_hostname in groups['splunk_deployment_server']
  
    - name: Copy deployment server install
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/copy_installed_apps.yml
      vars:
        apps: "{{ installed_apps }}"
        dest: "{{ splunk.app_paths.deployment }}"
      when: inventory_hostname in groups['splunk_deployment_server']
  
    - name: Disable installed apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/disable_installed_apps.yml
      when: inventory_hostname in groups['splunk_deployment_server']
    
    # CLUSTER MASTER - check for splunk_cluster_master role
    - name: Push apps to cluster master server
      vars:
        app_url: "{{ item }}"
      copy:
        src: "{{app_url}}"
        dest: "{{app_url}}"
      loop: "{{ splunk.apps_location }}"
      when: 
        - inventory_hostname in groups['splunk_cluster_master']
        - not app_url is match("^(https?|file)://.*")

    - name: Install cluster master apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/install_apps.yml
      vars:
        app_url: "{{ item }}"
      loop: "{{ splunk.apps_location }}"
      when: inventory_hostname in groups['splunk_cluster_master']

    - name: Find cluster master installed apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/find_installed_apps.yml
      when: inventory_hostname in groups['splunk_cluster_master']

    - name: Copy cluster master installed apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/copy_installed_apps.yml
      vars:
        apps: "{{ installed_apps }}"
        dest: "{{ splunk.app_paths.idxc }}"
      when: inventory_hostname in groups['splunk_cluster_master']

    - name: Apply cluster master cluster bundle
      include_tasks: ../splunk-ansible/roles/splunk_cluster_master/tasks/apply_cluster_bundle.yml
      when: inventory_hostname in groups['splunk_cluster_master']

    # DEPLOYER
    - name: Push apps to search head deployer server
      vars:
        app_url: "{{ item }}"
      copy:
        src: "{{app_url}}"
        dest: "{{app_url}}"
      loop: "{{ splunk.apps_location }}"
      when: 
        - inventory_hostname in groups['splunk_deployer']
        - not app_url is match("^(https?|file)://.*")
    
    - name: Install cluster master apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/install_apps.yml
      vars:
        app_url: "{{ item }}"
      loop: "{{ splunk.apps_location }}"
      when: inventory_hostname in groups['splunk_deployer']
    
    - name: Find installed deployer apps
      include_tasks: ../splunk-ansible/roles/splunk_common/tasks/find_installed_apps.yml
      when: inventory_hostname in groups['splunk_deployer']

    - include_tasks: ../splunk-ansible/roles/splunk_common/tasks/copy_installed_apps.yml
      vars:
        apps: "{{ installed_apps }}"
        dest: "{{ splunk.app_paths.shc }}"
      when: inventory_hostname in groups['splunk_deployer']

    - name: Apply shcluster bundle
      command: "{{ splunk.exec }} apply shcluster-bundle -target {{ cert_prefix }}://{{ splunk.search_head_captain_url }}:{{ splunk.svc_port }} -auth {{ splunk.admin_user }}:{{ splunk.password }} --answer-yes"
      become: yes
      become_user: "{{ splunk.user }}"
      no_log: "{{ hide_password }}"
      register: shcluster_bundle
      until: shcluster_bundle.rc == 0 or "Found zero deployable apps" in shcluster_bundle.stderr
      changed_when: shcluster_bundle.rc == 0
      failed_when: shcluster_bundle.rc != 0 and "Found zero deployable apps" not in shcluster_bundle.stderr
      retries: "{{ retry_num }}"
      delay: "{{ retry_delay }}"
      ignore_errors: true
      when: inventory_hostname in groups['splunk_deployer']

    - debug:
        msg: "WARNING: Applying shcluster bundle failed - proceeding anyways..."
      when: inventory_hostname in groups['splunk_deployer'] and shcluster_bundle.rc != 0