---
#########################################
# EXAMPLE STANDALONE DEPLOYMENT
#########################################
- hosts: local
  tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ntp_sync

- hosts: splunk_standalone
  # STRATEGY - free allows multiple server(s) and roles installed simultaneous and is required for service availability checks
  strategy: free
  gather_facts: True
  user: deployer
  pre_tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ntp_sync
  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      include_role: 
        name: post_config
  tasks:
    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: pre_config

    # STANDALONE - check for splunk_standalone role
    - name: Splunk splunk_standalone tasks
      include_role:
        name: splunk_standalone
      when: inventory_hostname in groups['splunk_standalone']