---
#########################################
# EXAMPLE DEPLOYMENT
#########################################

- hosts: local
  tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ../custom-roles/roles/ntp_sync

#########################################
# ROLE ASSIGNMENTS BY INVENTORY
#########################################

# Indexer cluster and search head cluster
# - hosts: splunk_license_master:splunk_cluster_master:splunk_deployer:splunk_search_head_captain:splunk_deployment_server:splunk_indexer:splunk_search_head

# Indexer cluster only
# - hosts: splunk_license_master:splunk_cluster_master:splunk_deployment_server:splunk_indexer:splunk_search_head

# Distributed with no cluster
# - hosts: splunk_license_master:splunk_deployment_server:splunk_indexer:splunk_search_head

# Standalone
# - hosts: splunk_standalone

#########################################
# DEPLOPY INDEXING/LICENSING/DEPLOYMENT
#########################################

- hosts: splunk_license_master:splunk_cluster_master:splunk_deployment_server:splunk_indexer
  # STRATEGY - free allows multiple server(s) and roles installed simultaneous and is required for service availability checks
  strategy: free
  gather_facts: True
  user: deployer
  
  environment:
    SPLUNK_SEARCH_HEAD_CAPTAIN_URL: "{{ groups['splunk_search_head_captain'][0] }}"
  
  pre_tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ../custom-roles/roles/ntp_sync

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: ../custom-roles/roles/pre_config

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../custom-roles/roles/post_config/tasks/main.yml

  tasks:

    # LICENSE MASTER- check for splunk_license_master role
    - name: Splunk splunk_license_master tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_license_master
      when: inventory_hostname in groups['splunk_license_master']

    # CLUSTER MASTER - check for splunk_cluster_master role
    - name: Splunk cluster_master tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_cluster_master
      when: inventory_hostname in groups['splunk_cluster_master']

    # STANDALONE - check for splunk_standalone role
    - name: Splunk splunk_standalone tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_standalone
      when: inventory_hostname in groups['splunk_standalone']

    # INDEXERS - check for splunk_indexer role
    - name: Splunk indexer tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_indexer
      when: inventory_hostname in groups['splunk_indexer']

    # DEPLOYMENT SERVER- check for splunk_deployment_server role
    - name: Splunk splunk_deployment_server tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_deployment_server
      when: inventory_hostname in groups['splunk_deployment_server']

######################################################
# DEPLOPY DEPLOYER/SEARCH HEAD CAPTAIN/SEARCH HEAD
######################################################

- hosts: splunk_deployer:splunk_search_head_captain:splunk_search_head
  # STRATEGY - free allows multiple server(s) and roles installed simultaneous and is required for service availability checks
  strategy: free
  gather_facts: True
  user: deployer
  
  environment:
    SPLUNK_SEARCH_HEAD_CAPTAIN_URL: "{{ groups['splunk_search_head_captain'][0] }}"

  pre_tasks:
    # Force an ntp update as service check requires time sync to work (should not be required in production)
    - name: Sync ntp
      include_role: 
        name: ../custom-roles/roles/ntp_sync

    # PRE CONFIG - Add users
    - name: Custom splunk server pre-config (setup user)
      include_role:
        name: ../custom-roles/roles/pre_config

  post_tasks:
    # Set ulimits by service (assumes systemd service deployment)
    - name: Post install config
      import_tasks: ../custom-roles/roles/post_config/tasks/main.yml

  tasks:
    # SEARCH HEAD CAPTAIN - check for splunk_search_head_captain role
    - name: Splunk splunk_search_head_captain tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_search_head_captain
      when: inventory_hostname in groups['splunk_search_head_captain']

    # SEARCH HEADS - check for splunk_search_head role
    - name: Splunk search_head tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_search_head
      when: inventory_hostname in groups['splunk_search_head']
    
    # DEPLOYER- check for splunk_deployer role
    - name: Splunk splunk_deployer tasks
      include_role:
        name: ../splunk-ansible/roles/splunk_deployer
      when: inventory_hostname in groups['splunk_deployer']
    
    