---
- hosts: splunk_distributed_monitoring_console
  gather_facts: True
  tasks:
    - name: Splunk splunk_distributed_monitoring_console tasks
      include_role:
        name: ../custom-roles/roles/splunk_distributed_monitoring_console