all:
    children:
      local:
        hosts:
          localhost:
        vars:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"
      splunk:
        vars:
          ansible_connection: ssh
          ansible_system: Linux
        children:
          splunk_search_head:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_search_head"
            hosts: 
              splksh1.psl.local:
          splunk_indexer:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_indexer"
            hosts: 
              splkidx1.psl.local:
          splunk_deployment_server:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_deployment_server"
            hosts: 
              splkdp1.psl.local:
          splunk_license_master:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_license_master"
            hosts: 
              splkdp1.psl.local:
          splunk_universal_forwarder:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_universal_forwarder"
            hosts: 
              splkuf1.psl.local: