all:
    children:
      local:
        hosts:
          localhost:
        vars:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"
      splunk:
        vars:
          ansible_connection: ssh
          ansible_system: Linux
        children:
          splunk_search_head:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_search_head"
            hosts: 
              splk-sh1.lab.local:
          splunk_indexer:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_indexer"
            hosts: 
              splk-idx1.lab.local:
          splunk_deployment_server:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_deployment_server"
            hosts: 
              splk-dp1.lab.local:
          splunk_license_master:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_license_master"
            hosts: 
              splk-dp1.lab.local:
          splunk_universal_forwarder:
            vars:
              splunk:
                hostname: "{{ inventory_hostname }}"
                role: "splunk_universal_forwarder"
            hosts: 
              splk-uf1.lab.local: