---
# tasks file for splunk_server (workaround for SPL-79993)

- name: Install httpd and mod_ssl
  package:
    name: 
      - httpd
      - mod_ssl
    state: present
  become: yes

- name: Create httpd ssl directory if it does not exist
  file:
    path: /etc/httpd/ssl
    state: directory
    mode: '0755'

- name: Copy splunk key to httpd cert directory
  copy:
    src: "{{ splunk.home }}/etc/auth/mycerts/splunk.key"
    dest: /etc/httpd/ssl/splunk.key
    remote_src: yes
  become: yes

- name: Copy splunk cert to httpd cert directory
  copy:
    src: "{{ splunk.home }}/etc/auth/mycerts/splunk.crt"
    dest: /etc/httpd/ssl/splunk.crt
    remote_src: yes
  become: yes

- name: Restrict access to cert material
  file:
    path: "{{ item }}"
    owner: apache
    group: apache
    mode: '0400'
  with_items:
    - "/etc/httpd/ssl/splunk.key"
    - "/etc/httpd/ssl/splunk.crt"
  become: yes

- name: Update httpd configuration for Splunk Web Proxy
  blockinfile:
    path: /etc/httpd/conf.d/ssl.conf
    insertafter: '<VirtualHost _default_:443>'
    block: |
      ProxyPass / https://127.0.0.1:8000/
      ProxyPassReverse / https://127.0.0.1:8000/
      SSLProxyEngine on
      SSLProxyVerify none
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off

- name: Validate the sudoers file before saving
  

- name: Update httpd SSLCertificateFile
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    state: present
    regexp: '^SSLCertificateFile'
    line: 'SSLCertificateFile /etc/httpd/ssl/splunk.crt'

- name: Update httpd SSLCertificateKeyFile
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    state: present
    regexp: '^SSLCertificateFile'
    line: 'SSLCertificateKeyFile /etc/httpd/ssl/splunk.key'

- name: Update httpd configuration for Splunk Web Proxy ServerName
  copy:
    content: |
      ServerName localhost      
    dest: /etc/httpd/conf.d/servername.conf   

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Enable service httpd, and not touch the state
  service:
    name: httpd
    enabled: yes
  become: yes

- name: Start service httpd, if not started
  service:
    name: httpd
    state: reloaded
  become: yes