---
# tasks file for splunk_server (workaround for SPL-79993)

- name: Install httpd and mod_ssl
  package:
    name: 
      - httpd
      - mod_ssl
    state: present
  become: yes

- name: Update httpd configuration for Splunk Web Proxy
  blockinfile:
    path: /etc/httpd/conf.d/ssl.conf
    insertafter: '<VirtualHost _default_:443>'
    block: |
      ProxyPass / https://127.0.0.1:8000/
      ProxyPassReverse / https://127.0.0.1:8000/
      SSLProxyEngine on
      SSLProxyVerify none
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off

- name: Enable service httpd, and not touch the state
  service:
    name: httpd
    enabled: yes
  become: yes

- name: Start service httpd, if not started
  service:
    name: httpd
    state: reloaded
  become: yes