---
- name: Set ulimits for splunk user
  copy:
    content: |
      splunk soft nofile 64000
      splunk hard nofile 64000
      splunk soft nproc 8192
      splunk hard nproc 8192
    dest: /etc/security/limits.d/10-splunk.conf
  become: yes
